name: Github Actions for Releases

on:
  push:
    tags:
    - "*"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Setup golang
      uses: actions/setup-go@v3
      with:
        go-version: '>=1.19'
        check-latest: true
    - name: Build and package with GoReleaser
      uses: goreleaser/goreleaser-action@v3
      with:
        distribution: goreleaser
        version: latest
        args: --snapshot --rm-dist
    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          dist/checksums.txt
          dist/*.tar.gz
